### ISSUE TITLE
Make the pause button, actually pause?

### ISSUE THREAD

**Issue by konstantinmvelkov** [konstantinmvelkov/DZC#13]
Currently, input from the keyboard is still read and also lava still rising, under pause button clicked. If we have some time left it would be a nice fix.

**Comment by gabrielazanova** [comment]
I dont see this issue on the board for some reason, otherwise yes

**Comment by BramHav** [comment]
It is working now. I tested it on a random selection of levels, but I believe it should work on all of them.
